### ISSUE TITLE
error deleting cluster in 3.10

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/casl-ansible#318] opened 2018-10-07 16:48 UTC
I'm getting this error running the `delete-cluster.yml` playbook in 3.10 with the OSP provisioner:
```TASK [../../../galaxy/openshift-ansible/roles/openshift_openstack : validate the Heat template] *******************************************************************************************************************
task path: /tmp/git/casl-ansible/galaxy/openshift-ansible/roles/openshift_openstack/tasks/provision.yml:12
Sunday 07 October 2018  16:44:15 +0000 (0:00:01.493)       0:00:08.680 ******** 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'stack_template_path' is undefined\n\nThe error appears to have been in '/tmp/git/casl-ansible/galaxy/openshift-ansible/roles/openshift_openstack/tasks/provision.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: validate the Heat template\n  ^ here\n"}```
the error seems to be related to a missing or badly positioned file.

**Comment by oybed** [comment] 2018-10-15 19:10
Duplicate of #300 - closing

**Closed by oybed** 2018-10-15 19:10 UTC
Labels: OpenStack, duplicate
